### ISSUE TITLE
Readme rollup-plugin-url mention

### ISSUE THREAD

**Issue by mcshaz** [maxdavidson/rollup-plugin-sourcemaps#105]
On windows filesystems, this plugin only finds the .map file pointed to with the `//# sourceMappingURL=` directive if the rollup-plugin-url plugin is added. This would also be great to have in the readme. 

Thanks for your plugin!

**Comment by maxdavidson** [comment]
Thank you for pointing out it doesn't work in Windows. I don't think recommending `@rollup/plugin-url` is the right approach, since that's more of hack and I'd rather fix the path resolution here instead. I created #116 to track this issue

**Comment by mcshaz** [comment]
That was actually the direction I was going in my fork of this repo, but wasn't actually sure if/when this issue would be seen. Thanks - I'll post further thoughts in #116
