### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by levrik** [maxdavidson/rollup-plugin-sourcemaps#84]
Hey. The plugin just doesn't work.
Before using the plugin I got at least source mapping to the built file of a dependency.
Now I just get nothing.

```js
import babel from 'rollup-plugin-babel';
import commonjs from 'rollup-plugin-commonjs';
import resolve from 'rollup-plugin-node-resolve';
import sourcemaps from 'rollup-plugin-sourcemaps';

import pkg from './package.json';

export default {
  input: 'src/index.js',
  output: [
    {
      file: pkg.main,
      format: 'cjs',
      sourcemap: true,
      compact: true,
      exports: 'named'
    },
    {
      file: pkg.module,
      format: 'es',
      sourcemap: true,
      compact: true,
      exports: 'named'
    }
  ],
  plugins: [
    babel({
      babelrc: false,
      exclude: '../../node_modules/**',
      presets: [
        ['@babel/env', {
          exclude: ['transform-regenerator']
        }]
      ],
      plugins: [
        '@babel/proposal-class-properties'
      ]
    }),
    commonjs(),
    resolve(),
    sourcemaps()
  ]
};
```

Without this plugin:
![image](https://user-images.githubusercontent.com/9491603/57703346-274ff400-7660-11e9-8a1c-16065f43fee1.png)

With this plugin:
![image](https://user-images.githubusercontent.com/9491603/57703296-11daca00-7660-11e9-9b56-99347252bce0.png)

I would expect to get source mapping to `document-canvas-vanilla/src` instead.

**Comment by maxdavidson** [comment]
This plugin implements a custom load hook as described [here](https://rollupjs.org/guide/en#hooks). Perhaps the Babel plugin is interfering? Looks like Babel already has this capability built in by using the [`inputSourceMap`](https://babeljs.io/docs/en/options#inputsourcemap), have you tried that?

**Comment by levrik** [comment]
@maxdavidson Ah, interesting that Babel has this built-in.
Anyway, you pointed me to a misconfiguration of Babel. Actually `document-canvas-vanilla/src` should be excluded in Babel. If I exclude this, everything works fine.
