### ISSUE TITLE
Add typescript definition file to the package.

### ISSUE THREAD

**Issue by MicahZoltu** [maxdavidson/rollup-plugin-sourcemaps#87]
It makes me sad that a project presumably designed to work with TypeScript doesn't include definition files for itself.  😢 
```typescript
// Could not find a declaration file for module 'rollup-plugin-sourcemaps'.
import sourcemaps from 'rollup-plugin-sourcemaps'
sourcemaps()
```

Please add a .d.ts file next to index.js in the distributed package!

**Comment by MicahZoltu** [comment]
I believe this is all that is needed for the definition files:

`dist/rollup-plugin-sourcemaps.d.ts`
```typescript
import {Plugin} from 'rollup';
declare function sourcemaps(): Plugin;
export = sourcemaps
```
`dist/rollup-plugin-sourcemaps.es.d.ts`
```typescript
import {Plugin} from 'rollup';
export function sourcemaps(): Plugin;
```

I don't know how to get those into the build process, otherwise I would submit a PR.

**Comment by maxdavidson** [comment]
Sorry for late response, but we now ship our own type definitions since v0.5.0 is written in TypeScript
